version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    networks:
      - nginx_net
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nginx_net
networks:
  nginx_net:
    external: true
volumes:
  postgres_data:
