services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movdb
    volumes:
      - /srv/dev-disk-by-uuid-1735d6ab-2a75-4dc4-91a9-b81bb3fda73d/Servicios/MovimientosDinero/postgres_data/postgres_data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

    networks:
      - nginx_net
networks:
  nginx_net:
    external: true
volumes:
  postgres_data:
